pref_label: "Keyword"
description: "Keyword attached to the resource."
members:
  - pref_label: "After Dark"
    description: ""
  - pref_label: "ArtFEED"
    description: ""
  - pref_label: "Night Heist"
    description: ""
  - pref_label: "Community Associates"
    description: ""
  - pref_label: "Evening Associates"
    description: ""
  - pref_label: "New employee orientation"
    description: ""
  - pref_label: "Conservation in progress"
    description: ""
  - pref_label: "Labs/office photography"
    description: ""
  - pref_label: "Employee Holiday Party"
    description: ""
  - pref_label: "Chairman's Awards"
    description: ""
  - pref_label: "Department Party"
    description: ""
  - pref_label: "Gala"
    description: ""
  - pref_label: "Gallery Reception"
    description: ""
  - pref_label: "Portrait"
    description: ""
  - pref_label: "Installation in-progress"
    description: ""
  - pref_label: "Chicago Object Study Initiative (COSI)"
    description: ""
  - pref_label: "Society for Contemporary Art"
    description: ""
  - pref_label: "Asian Art Society"
    description: ""
  - pref_label: "Antiquarian Society"
    description: ""
  - pref_label: "Facade Banners"
    description: ""
  - pref_label: "Installed Exhibition Marketing"
    description: ""
  - pref_label: "Wreathing Lions"
    description: "Images of marketing installed on trains or at bus stops."
  - pref_label: "Helmet Lions"
    description: ""
  - pref_label: "Parade"
    description: ""
  - pref_label: "Shop Windows"
    description: ""
  - pref_label: "AIC Architecture: Building"
    description: ""
  - pref_label: "AIC Architecture: Gardens"
    description: ""
  - pref_label: "AIC Architecture: Views"
    description: ""
  - pref_label: "AIC Architecture: Renovation"
    description: ""
  - pref_label: "Needs Revision"
    description: "Add this keyword to assets that need edits depending on features not currently available in LAKE."
  - pref_label: "AIC Architecture: Facade"
    description: ""
