# Environment variable configuration file used by Figaro
#
# This will be overwritten during deployment.
# Used to set the temporary directories
#
# Ex:
# production:
#   TMPDIR: "path/to/dir"
development:

test:
  citi_api_uid: "citi_api_uid"
  citi_api_password: "citi_api_password"
  citi_api_endpoint: "https://citiworker"
  citi_api_ssl_verify: "false"

