development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_DEVELOPMENT_ROOT'] || "http://localhost:8986" %>/fcrepo/rest
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: <%= ENV['FCREPO_TEST_ROOT'] || "http://localhost:8986" %>/fcrepo/rest
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://localhost:8986/rest
  base_path: /prod
